# Generated by Django 2.0.3 on 2018-05-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='foods Name :')),
                ('type', models.CharField(max_length=30, verbose_name='foods type :')),
                ('article', models.CharField(max_length=250, verbose_name='food article :')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
