# Generated by Django 2.0.3 on 2018-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Fast Food', 'Fast Food'), ('Chaines', 'Chaines Food'), ('Thai Food', 'Thai Food'), ('Vegetables Food', 'Vegetables Food'), ('Rices Foods', 'Rices Foods'), ('other', 'Other')], max_length=30, verbose_name='foods type :'),
        ),
    ]
