# Generated by Django 2.0.3 on 2018-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_foods', '0002_auto_20180504_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Fast Food', 'Fast Food'), ('Chaines', 'Chaines Food'), ('Thai Food', 'Thai Food'), ('Vegetables Food', 'Vegetables Food'), ('Rices Foods', 'Rices Foods'), ('soup', 'soup'), ('Fried Chicken', 'Fried Chicken'), ('Meal', 'Meal'), ('Grilled', 'Grilled'), ('Beverage', 'Beverage'), ('other', 'Other')], max_length=30, verbose_name='foods type :'),
        ),
    ]
