# Generated by Django 2.0.3 on 2018-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_foods', '0005_auto_20180512_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='foods Name :')),
                ('type', models.CharField(choices=[('Fast Food', 'Fast Food'), ('Dinner Foods', 'Dinner Foods'), ('Lunch Food', 'Lunch Food'), ('Rices Foods', 'Rices Foods'), ('soup', 'soup'), ('Fried Chicken', 'Fried Chicken'), ('Grilled', 'Grilled'), ('other', 'Other')], max_length=30, verbose_name='foods type :')),
                ('article', models.CharField(max_length=250, verbose_name='food article :')),
                ('image', models.FileField(upload_to='')),
                ('Offer_price', models.IntegerField(default=0, verbose_name='Offer_price')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='offer_price',
        ),
    ]
