# Generated by Django 2.0.3 on 2018-05-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_foods', '0006_auto_20180514_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferFoods',
        ),
    ]
