# Generated by Django 2.0.3 on 2018-05-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_foods', '0008_offerfoods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferFoods',
            new_name='OfferFood',
        ),
    ]
