# Generated by Django 2.0.3 on 2018-06-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_foods', '0009_auto_20180514_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerfood',
            name='article',
        ),
        migrations.RemoveField(
            model_name='offerfood',
            name='image',
        ),
        migrations.RemoveField(
            model_name='offerfood',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offerfood',
            name='type',
        ),
        migrations.AddField(
            model_name='offerfood',
            name='all_food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='all_foods.Food'),
            preserve_default=False,
        ),
    ]
