# Generated by Django 2.0.3 on 2018-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_foods', '0010_auto_20180626_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Fast', 'Fast Food'), ('Dinner', 'Dinner Foods'), ('Lunch', 'Lunch Food'), ('Rices Foods', 'Rices Foods'), ('soup', 'soup'), ('FriedChicken', 'Fried Chicken'), ('Grilled', 'Grilled'), ('other', 'Other')], max_length=30, verbose_name='foods type :'),
        ),
    ]
