# Generated by Django 3.1.4 on 2020-12-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_foods', '0011_auto_20180717_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Fast', 'Fast'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Rices Foods', 'Rices'), ('soup', 'soup'), ('FriedChicken', 'FriedChicken'), ('Grilled', 'Grilled'), ('other', 'Other')], max_length=30, verbose_name='foods type :'),
        ),
    ]
